name: Build Laravel application using Docker

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  CONTAINER_NAME: "nickpocketbot"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: mukolla/tgbot
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Deploy to my Server via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST_SERVER_IP }}
          username: ${{ secrets.HOST_SERVER_USERNAME }}
          key: ${{ secrets.HOST_SERVER_SSHKEY }}
          envs: CONTAINER_NAME
          script: |
            # Stop running container
            docker stop $(echo $CONTAINER_NAME) || true
            
            # Remove old container
            docker rm $(echo $CONTAINER_NAME) || true
            
            # Set env variables
            export TOKEN=${{ secrets.POCKET_TOKEN }}
            export CONSUMER_KEY=${{ secrets.POCKET_CONSUMER_KEY }}
            export AUTH_SERVER_REDIRECT_URL=${{ secrets.POCKET_AUTH_SERVER_URL }}
            
            # Run a new container from a new image
            docker run -e TOKEN -e CONSUMER_KEY -e AUTH_SERVER_REDIRECT_URL -d \
            --restart always \
            --publish 8183:8183 \
            --name $(echo $CONTAINER_NAME) \
            mukolla/tgbot:latest